### ISSUE TITLE
Destroys Mini Sentries

### ISSUE THREAD

**Issue by torridgristle** [Frenzoid/TF2_InvisibleWeaponsFix#1]
Removing the Gunslinger from the player with TF2_RemoveAllWeapons destroys Mini Sentries.

**Comment by Frenzoid** [comment]
Hello! First of all, i want to thank you for contacting me about this issue.

Could you please apport more info about the environment you're running? 
Specifically: Sourcemod version, and TF2 gamemode.

The plugins that i make are solely tested on a server running [FF2](https://github.com/Batfoxkid/FreakFortressBat) ([ARENA](https://wiki.teamfortress.com/wiki/Arena)) gamemode, so, for now, i can only 100% assure that it works on that gamemode.

Yet, what's odd to me is that, the `TF2_RemoveAllWeapons` function is only called when the `teamplay_round_start` event triggers, so it should be imposible for an engineer to place a mini sentry before the round starts, thats why i need more info about in which conditions youre running the plugin.


Best regars!


PD: I've checked the [original version](https://forums.alliedmods.net/showthread.php?t=298391), and that one triggers when the player spawns, not sure if you're using that version, or mine, since, in that case, it might be possible that a sentry placed by any  engineer would get destroyed upon player spawn.

**Comment by torridgristle** [comment]
Oh okay, yeah, it was the original version, not this one. Sorry, thought it was the same.

**Comment by Frenzoid** [comment]
Its all good, sadly, there's no persistent way to fix the invisible weapons bug.

TF2's source code is too spaguettied, and sourcemod is already doing anough to make plugin development the most confortable as posible for devs.

The plugin that i server could work on arenas, but the moment the players respawn they are up to the chance to get invisible weapons again. 

Anyway, if you have any suggestion or question don't hesitate to open another ticket! 

Best regars! :D
